services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '54322:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  books:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      API_PORT: 9000
    ports:
      - '9000:9000'
    depends_on:
      - db

volumes:
  db_data: